### ISSUE TITLE
[BUG/ISSUE] 40-level GCClassic fullchem restart files are not up to date

### ISSUE THREAD

**Issue by flavioquadros** [geoschem/geos-chem#1191]
### What institution are you from?
Delft University of Technology - Faculty of Aerospace Engineering

### Description of the problem
The restart files [available](http://atmos.earth.rochester.edu/input/gc/ExtData/GCAP2_RESTARTS/) for fullchem simulations using GCAP 2.0 are missing some variables expected by the latest version of GEOS-Chem ([present in these restart files](http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/)), causing a "field missing" error when starting up a run. These are the variables available only on the more recent files:
`hyam, hybm, hyai, hybi, P0, Met_TropLev, Met_BXHEIGHT, Met_DELPDRY, SpeciesRst_HMS, SpeciesRst_HSO3m, SpeciesRst_SO3mm, SpeciesRst_C2H2, SpeciesRst_C2H4, SpeciesRst_ETHN, SpeciesRst_ETHP, lat_bnds, lon_bnds, SpeciesRst_ETO, SpeciesRst_ETOO, SpeciesRst_AONITA, SpeciesRst_AROMP4, SpeciesRst_AROMP5, SpeciesRst_AROMRO2, SpeciesRst_BALD, SpeciesRst_BENZO, SpeciesRst_BENZO2, SpeciesRst_BENZP, SpeciesRst_BZCO3, SpeciesRst_BZCO3H, SpeciesRst_BZPAN, SpeciesRst_CSL, SpeciesRst_MCT, SpeciesRst_NPHEN, SpeciesRst_PHEN`

I'd guess this [make_40L.ncl](http://atmos.earth.rochester.edu/input/gc/ExtData/GCAP2_RESTARTS/make_40L.ncl) script in the Rochester server was used before to make the conversion, but it is not accessible. This is probably something that needs fixing for #893. After I added the missing fields from the current 72-level restart file into the 40-level one, the model ran normally here. But it would be good if someone could use that previous conversion script to produce an "official" version of the restart file that works out of the box.

### GEOS-Chem version
13.3.4

**Comment by ltmurray** [comment]
@yantosca, I'm not seeing newer restart files on the WUSTL or Harvard servers for GCClassic than GC_13.0.0.  This issue should impact all GCClassic users, not just GCAP2.

**Comment by yantosca** [comment]
@ltmurray @flavioquadros, the GC_13.0.0 indicates that those were from the 10-year benchmark done with 13.0.0.  Restarts for other more recent model versions are in the more recent vYYYY-MM folders.  For example, the 13.3.0 restart files are in http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/v2021-09/.

**Comment by ltmurray** [comment]
v2022-01 only contains GCHP restart files, which is presumably the version with acetylene et al.?

**Comment by yantosca** [comment]
This is a list of the restart file folder locations that the `download_data.py` script will pull from, if it makes it clearer.
``yml
restarts:
  root: GEOSCHEM_RESTARTS/
  aerosol:
    remote: v2021-09/GEOSChem.Restart.fullchem.20190101_0000z.nc4
    local: GEOSChem.Restart.20190101_0000z.nc4
  fullchem:
    remote: v2021-09/GEOSChem.Restart.fullchem.20190701_0000z.nc4
    local: GEOSChem.Restart.20190701_0000z.nc4
  mercury:
    remote: v2021-12/GEOSChem.Restart.Hg.20190101_0000z.nc4
    local: GEOSChem.Restart.20190101_0000z.nc4
  tomas15:
    remote: v2021-12/GEOSChem.Restart.TOMAS15.20190701_0000z.nc4
    local: GEOSChem.Restart.20190701_0000z.nc4
  tomas40:
    remote: v2021-12/GEOSChem.Restart.TOMAS40.20190701_0000z.nc4
    local: GEOSChem.Restart.20190701_0000z.nc4
  transporttracers:
    remote: GC_13.0.0/GEOSChem.Restart.TransportTracers.20190101_0000z.nc4
    local: GEOSChem.Restart.20190101_0000z.nc4
  other:
    remote: v2020-02/initial_GEOSChem_rst.2x25_@SUFFIX@
    local: GEOSChem.Restart.20190701_0000z.nc4
```
I think v2022-02 contains GCHP restart files with all species (because a recent update to MAPL is taking away the ability to bootstrap tracers not found in the restart file).

**Comment by ltmurray** [comment]
Okay, thanks — I didn't realize vYYYY-MM didn't update all restart files at the same time.

I've just vertically re-gridded and uploaded the restart files since GCAP2 launched to the Rochester server. @yantosca if the GCST could let me know when those get updated in the future, I can process at the same time.

@flavioquadros , please feel free to send me an email so I can add your project to the list of [GCAP2 users](http://atmos.earth.rochester.edu/giss-gc/)!

**Comment by ltmurray** [comment]
Also, it looks like download_data.yml needs to be modified for GCAP2 run directories to point to the correct restart files

```
restarts:
  root: GCAP2_RESTARTS/
  aerosol:
    remote: v2021-09/40L/GCAP2.Restart.fullchem.20190101_0000z.nc4
    local: GEOSChem.Restart.20190101_0000z.nc4
  fullchem:
    remote: v2021-09/40L/GCAP2.Restart.fullchem.20190701_0000z.nc4
    local: GEOSChem.Restart.20190701_0000z.nc4
  tomas15:
    remote: v2021-09/40L/GCAP2.Restart.TOMAS15.20190701_0000z.nc4
    local: GEOSChem.Restart.20190701_0000z.nc4
  tomas40:
    remote: v2021-09/40L/GCAP2.Restart.TOMAS40.20190701_0000z.nc4
    local: GEOSChem.Restart.20190701_0000z.nc4
  transporttracers:
    remote: GC_13.0.0/40L/GCAP2.Restart.TransportTracers.20190101_0000z.nc4
    local: GEOSChem.Restart.20190101_0000z.nc4
  other:
    remote: v2020-02/40L/initial_GCAP2_rst.2x25_@SUFFIX@
    local: GEOSChem.Restart.20190701_0000z.nc4
```
