### ISSUE TITLE
[BUG/ISSUE] Nested run on 14.0.0-rc.2 on AWS 

### ISSUE THREAD

**Issue by arianatribby** [geoschem/geos-chem#1373]
### What institution are you from?
Caltech

### Description of the problem
It is my first time attempting a nested simulation. I created a run directory specifically for a nested simulation and also edited the geoschem_config.yml . When the run starts to read HISTORY.rc, it stops without any errors. I changed verbose/warning to 3 in HEMCO_Config.rc and also debug_printout on geoschem_config.yml to true, but no additional errors or comments are printed out where the run stops. Here is the output to the terminal during the run right before the run stops: 

```
$$ Finished Reading Linoz Data $$

HISTORY (INIT): Opening ./HISTORY.rc
(base) ubuntu@ip-172-31-65-111:
```

### Description of troubleshooting performed
Since there is no error from GEOS-Chem, perhaps it is on the software or hardware end. I have a cx5.9 instance (36 cpu and 72 Gb memory plus 400 Gb storage). I don't see a problem with running out of cpu or memory on aws cloudwatch. However, I am using ami-0491da4eeba0fe986 - is this the appropriate AMI for this run? 

### GEOS-Chem version
14.0.0-rc.2 AWS 

### Description of modifications
Here are the edits to config files for the nested run: 
```
#============================================================================
# Simulation settings
#============================================================================
simulation:
  name: fullchem
  start_date: [20160701, 010000]
  end_date: [20160701, 030000]
  root_data_dir: /home/ubuntu/ExtData
  met_field: MERRA2
  species_database_file: ./species_database.yml
  debug_printout: true
  use_gcclassic_timers: false

#============================================================================
# Grid settings
#============================================================================
grid:
  resolution: 0.5x0.625
  number_of_levels: 72
  longitude:
    range: -180.0 10.0
    center_at_180: true
  latitude:
    range: 10.0 90.0
    half_size_polar_boxes: true
  nested_grid_simulation:
    activate: true
    buffer_zone_NSEW: [3, 3, 3, 3]
```

I followed the steps to create the run directory for nested using this link: 
https://geos-chem.readthedocs.io/en/latest/gcc-guide/02-build/rundir-fullchem.html?highlight=nested

(So I selected 0.5x0.625 resolution during the run dir creation, then selected custom grid domain). 

### Log files
[run.log.txt](https://github.com/geoschem/geos-chem/files/9561477/run.log.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/9561478/HISTORY.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/9561479/HEMCO_Config.rc.txt)
[geoschem_config.yml.txt](https://github.com/geoschem/geos-chem/files/9561480/geoschem_config.yml.txt)

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:
