### ISSUE TITLE
[BUG/ISSUE] ND51 satellite not working in 14.0.0

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1467]
The ND51 diagnostic does not seem to recognize when it is turned on in geoschem_config.yml when using GEOS-Chem 14.0.0-rc.3. ND51b works as expected. I verified that I compiled with the `-DBPCH_DIAG=y` option. In my geoschem_config.yml file, I have:

```
    ND51_satellite:
      activate: true
      output_file: Satellite/ts_9_30am.YYYYMMDD.bpch
      tracers:
        - 186
        - 511
        - 507
	- 176
        - 40
        - 56
      UTC_hour_for_write: 0
      averaging_period_in_LT: [9, 10]
      IMIN_and_IMAX_of_region: [1, 72]
      JMIN_and_JMAX_of_region: [1, 46]
      LMIN_and_LMAX_of_region: [1, 72]

    ND51b_satellite:
      activate: true
      output_file: Satellite/ts_1_30pm.YYYYMMDD.bpch
      tracers:
        - 186
        - 511
        - 507
        - 176
        - 40
        - 56
      UTC_hour_for_write: 1
      averaging_period_in_LT: [13, 14]
      IMIN_and_IMAX_of_region: [1, 72]
      JMIN_and_JMAX_of_region: [1, 46]
      LMIN_and_LMAX_of_region: [1, 72]
```

However, in the log file I have:

```
ND51 TIMESERIES SETTINGS (when -DBPCH_DIAG=y)
---------------------------------------------
Turn on ND51 timeseries?    :     F
ND51 timeseries file name   : Satellite/ts_9_30am.YYYYMMDD.bpch
ND51 timeseries tracers     :  186 511 507  40  56
ND51 hour to write to disk  :   0.0
ND51 averaging period [GMT] :   9.0 10.0
ND51 longitude limits       :     1   72
ND51 latitude  limits       :     1   46
ND51 altitude  limits       :     1   72

ND51b TIMESERIES SETTINGS (when -DBPCH_DIAG=y)
----------------------------------------------
Turn on ND51b timeseries?   :     T
ND51b timeseries file name  : Satellite/ts_1_30pm.YYYYMMDD.bpch
ND51b timeseries tracers    :  186 511 507 176  40  56
ND51b hour to write to disk :   1.0
ND51b averaging period [GMT]:  13.0 14.0
ND51b longitude limits      :     1   72
ND51b latitude  limits      :     1   46
ND51b altitude  limits      :     1   72
```

So `Turn on ND51 timeseries : F` even though `activate: true` in the configuration file.
