### ISSUE TITLE
WetLossLS netcdf file doesn't open 

### ISSUE THREAD

**Issue by laura-hyesung-yang** [geoschem/geos-chem#1761]
### Name and Institution (Required)

Name: Laura Yang
Institution: Harvard University

### Description of your issue or question

I'm trying to output the wet loss rate via rainout and washout in the large-scale wet deposition of MP species in GEOS-Chem version 13.3.4. I'm outputting only 'WetLossLS_MP' in the HISTORY.rc for the WetLossLS diagnostic. However, when I try to open the output "GEOSChem.WetLossLS.20160101_0000z.nc4" file, I get the error stating "can't recognize the format of input file GEOSChem.WetLossLS.20160101_0000.nc4. It's odd as I am able to output 'WetLossConv_MP' and open its related file without an issue. I believe file writing is the issue as the model runs successfully and other outputs are viewable. Below is the MP species information from 'species_database.yml'.

```yaml
MP:
  Background_VV: 4.0e-15
  Formula: CH3OOH
  FullName: Methyl hydro peroxide
  Henry_CR: 5200.0
  Henry_K0: 2.94e+2
  Is_Advected: true
  Is_Gas: true
  Is_Photolysis: true
  Is_WetDep: true
  MW_g: 48.05
  WD_RetFactor: 2.0e-2
```
Thank you!
