### ISSUE TITLE
Question about adding some new species and inventory into GC

### ISSUE THREAD

**Issue by Fearlessssssss** [geoschem/geos-chem#1783]
### Name and Institution (Required)

Name:Tyler
Institution:THU

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

Hi GCST, I'm new to GC. My version is 14.1.1. I'm trying to adding a new species(base emissions) and inventory for simulation, but I am confused about the way species database.yml in geoschem match with HECO_Config.rc and HEMCO_Diagn_rc in HEMCO.  I have read the GeosCore but failed to find the part about read the specific species , it seem like that when run a new simulation, a HcoID will be automatically allocated. So I have tried to directly modified the species database.yml, HECO_Config.rc and HEMCO_Diagn_rc in HEMCO, but the new species was not recognized. Can someone give me some advices about what should I do? Thanks a lot.

**Comment by yantosca** [comment]
Thanks for writing @Fearlessssssss.  So when you use HEMCO within GEOS-Chem, HEMCO will take the metadata definitions (e.g. name, molecular weight, etc) that you have defined in the `species_database.yml` file.  So it should be enough to add the new species information to `species_database.yml`

We would point you to our ReadTheDocs documentation:

- [View GEOS-Chem species properties]https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/species-guide.html)
- [The HEMCO_Config.rc file](https://geos-chem.readthedocs.io/en/latest/gcclassic-user-guide/hemco-config.html)

**Comment by Fearlessssssss** [comment]
I have checked the file OutputDir-geoschem_species_metadata.yml, but the new species which I have added in  species_database.yml is not in the list. 


| |
chenjing
|
|
***@***.***
|
---- Replied Message ----
| From | Bob ***@***.***> |
| Date | 5/2/2023 22:21 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [geoschem/geos-chem] Question about adding some new species and inventory into GC (Issue #1783) |

Thanks for writing @Fearlessssssss. So when you use HEMCO within GEOS-Chem, HEMCO will take the metadata definitions (e.g. name, molecular weight, etc) that you have defined in the species_database.yml file. So it should be enough to add the new species information to species_database.yml

We would point you to our ReadTheDocs documentation:

[View GEOS-Chem species properties]https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/species-guide.html)
The HEMCO_Config.rc file

**Comment by Fearlessssssss** [comment]
[geoschem_config.txt](https://github.com/geoschem/geos-chem/files/11375006/geoschem_config.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/11375007/HEMCO_Config.txt)
[species_database.txt](https://github.com/geoschem/geos-chem/files/11375008/species_database.txt)
[slurm-251.txt](https://github.com/geoschem/geos-chem/files/11375009/slurm-251.txt)
 
My simulation type is aerosol. These are my files. Thanks!

**Comment by yantosca** [comment]
I see the problem.  You would need to add your new species (MHNNO3) to the list of transported species in `geoschem_config.yml`.

```yaml
 transport:
    gcclassic_tpcore:                 # GEOS-Chem Classic only
      activate: true                  # GEOS-Chem Classic only
      fill_negative_values: true      # GEOS-Chem Classic only
      iord_jord_kord: [3, 3, 7]       # GEOS-Chem Classic only
    transported_species:
      - BCPI
      - BCPO
      - DMS
      - DST1
      - DST2
      - DST3
      - DST4
      - H2O2
      - MSA
      - NH3
      - NH4
      - NIT
      - NITs
      - OCPI
      - OCPO
      - pFe
      - SALA
      - SALAAL
      - SALACL
      - SALC
      - SALCAL
      - SALCCL
      - SO2
      - SO4
      - SO4s
      - SOAP
      - SOAS
      - MHNNO3
  ```
