### ISSUE TITLE
Adding a new species (methanediol) to GEOS-Chem

### ISSUE THREAD

**Issue by laura-hyesung-yang** [geoschem/geos-chem#2101]
Name: Laura Yang
Institution: Harvard 

I'm adding a new species to the GEOS-Chem v13.3.4 model called methanediol (MDL). In the `species_database.yml`, I added  MDL species following HMHP species. 
```yaml
MDL:
  DD_F0: 1.0
  DD_Hstar: 1.3e+6
  Formula: HOCH2OH
  FullName: Methanediol
  Henry_CR: 5200.0
  Henry_K0: 8.1e+5
  Is_Advected: true
  Is_DryDep: true
  Is_Gas: true
  Is_WetDep: true
  MW_g: 64.05
  WD_RetFactor: 2.0e-2
```
In the `input.geos` file, I added MDL under `ADVECTED SPECIES MENU`. In`KPP/fullchem/fullchem.eqn`, I added the MDL under `#DEFVAR` section, added the reactions, and recompiled my KPP. I turned on the Boundary Condition collection in `HISTORY.rc` file. I also added MDL species as `SpeciesRST_MDL` in the Restart file.  However, when I run the model, I get the following error related to `mapData$slot2Id` in the GC.log (Attached photo). When I run the model without MDL, the model runs fine so I believe the error is related to adding MDL species. Could I ask for your help related to this issue? Thank you!

![Screenshot 2024-01-04 at 12 42 01 PM](https://github.com/geoschem/geos-chem/assets/42656706/2c4822e7-e09c-4388-b7f0-72139095bd92)
