### ISSUE TITLE
Inquiry Regarding Modification of Marine Primary Organic Aerosol (POA) Calculation and Data Abbreviations

### ISSUE THREAD

**Issue by ChenBHXMU** [geoschem/geos-chem#2405]
### Your name

Baihua Chen

### Your affiliation

Xiamen University

### Please provide a clear and concise description of your question or discussion topic.

Dear  @yantosca, 

I hope this message finds you well.

I am currently studying GEOS-Chem and am interested in modifying the calculation method for marine primary organic aerosol (POA). Could you please provide guidance on how to adjust the code for these modifications?

Additionally, I set up the calculation for marine POA when I used "./createRunDir.sh". I noticed that in the OutputDir file, there seems to be no data available for POA. Instead, I found data labeled as MOPO, MOPI, POx and PO2. Is there a guide or documentation available on the website that explains these abbreviations?

Thank you very much for your assistance.

Best regards,
Baihua Chen

**Comment by yantosca** [comment]
Thanks for writing @ChenBHXMU.  The species information is contained in the `species_database.yml` file:
```yaml
MOPI:
  DD_DvzAerSnow: 0.03
  DD_F0: 0.0
  DD_Hstar: 0.0
  Density: 1300.0
  Formula: C
  FullName: Hydrophilic marine organic carbon aerosol
  Is_Advected: true
  Is_Aerosol: true
  Is_DryDep: true
  Is_WetDep: true
  MW_g: 12.01
  WD_AerScavEff: 1.0
  WD_KcScaleFac: [1.0, 0.5, 1.0]
  WD_RainoutEff: [1.0, 0.0, 1.0]
  WD_RainoutEff_Luo: [0.4, 0.0, 1.0]
MOPO:
  DD_DvzAerSnow: 0.03
  DD_F0: 0.0
  DD_Hstar: 0.0
  Density: 1300.0
  Formula: C
  FullName: Hydrophobic marine organic carbon aerosol
  Is_Advected: true
  Is_Aerosol: true
  Is_DryDep: true
  Is_WetDep: true
  MW_g: 12.01
  WD_AerScavEff: 1.0
  WD_KcScaleFac: [0.5, 0.5, 0.5]
  WD_RainoutEff: [0.0, 0.0, 0.0]
POx:
  FullName: Dummy species to track production rate of Ox
  Is_Gas: true
  MW_g: 48.00
```
PO2 is probably another dummy species to track the production of O2.  It is not in the "out-of-the-box" run directory.  Maybe someone else added that.
