### ISSUE TITLE
Simulation of brown carbon 

### ISSUE THREAD

**Issue by sherryfjy** [geoschem/geos-chem#2539]
### Your name

Jingyi Fan

### Your affiliation

Nanjing University

### Please provide a clear and concise description of your question or discussion topic.

Hello, 
I want to use the GEOS-Chem model to investigate the light absorption efficiency of brown carbon and its direct radiative forcing.The simulation type I chose is full chemistry.
 However, I noticed that the output file GEOSChem.SpeciesConc.xxxxxxxx_0000z.nc4 does not include brown carbon. In the run folder of GEOS-Chem, there is a switch for brown carbon in the geoschem_config.rc file under the aerosols settings. If the brown carbon switch is true, which output files and species will be affected?

In the geoschem_config.rc file, the aerosols settings are as follows:
```yaml
#============================================================================
# Settings for GEOS-Chem aerosols
#============================================================================
aerosols:

  carbon:
    activate: true
    brown_carbon: false
    enhance_black_carbon_absorption:
      activate: true
      hydrophilic: 1.5
      hydrophobic: 1.0
```
