### ISSUE TITLE
ValueError: Could not locate the ExtData folder in your local disk space!

### ISSUE THREAD

**Issue by INDjyt** [geoschem/geos-chem#2584]
### Your name

Jiang Yutong

### Your affiliation

China University of Geosciences Beijing或China University of Geosciences

### What happened? What did you expect to happen?

I completed the dry-run simulation following the getting started guide. However, when I wanted to download data from the dry-run output, I ran "./download_data.py log.dryrun geoschem+http", but an error was reported：
```console
Traceback (most recent call last):
  File "./download_data.py", line 788, in <module>
    main()
  File "./download_data.py", line 782, in main
    download_the_data(parse_args())
  File "./download_data.py", line 665, in download_the_data
    paths = extract_pathnames_from_log(args)
  File "./download_data.py", line 165, in extract_pathnames_from_log
    raise ValueError(msg)
ValueError: Could not locate the ExtData folder in your local disk space!
```
It seems that I am missing a folder named ExtData, but I didn't find any relevant content about ExtData in the getting started guide. I comprehensively searched all my folders and only found a folder named ExtData.rc.templates at the path /home/jyt/GCClassic/src/GEOS-Chem/run/GCHP/, which contains 5 files, namely ExtData.rc.carbon, ExtData.rc.CO2, ExtData.rc.fullchem, ExtData.rc.tagO3 and ExtData.rc.TransportTracers.

I checked the geoschem_config.yml file, and among them:
```yaml
# Simulation settings
#============================================================================
simulation:
  name: carbon
  start_date: [20190101, 000000]
  end_date: [20190201, 000000]
  root_data_dir: ExtData
  met_field: MERRA2
  species_database_file: ./species_database.yml
  species_metadata_output_file: OutputDir/geoschem_species_metadata.yml
  verbose:
    activate: false
    on_cores: root       # Allowed values: root all
  use_gcclassic_timers: false
```

### What are the steps to reproduce the bug?
I tried to change root_data_dir to ExtData.rc.templates, but running "./download_data.py log.dryrun geoschem+http" still reported the same error, which really confused me. I also tried to create a new folder named ExtData, but it didn't work.
Before posting, I found two problem reports that seemed very relevant, but my problem seems to be different from theirs.
So could you give me some suggestions to solve the problem? Thank you very much.

### Please attach any relevant configuration and log files.
[HEMCO_Config.txt](https://github.com/user-attachments/files/17866751/HEMCO_Config.txt)
[HEMCO_Diagn.txt](https://github.com/user-attachments/files/17866752/HEMCO_Diagn.txt)
[HISTORY.txt](https://github.com/user-attachments/files/17866753/HISTORY.txt)
[log.txt](https://github.com/user-attachments/files/17866754/log.txt)
[download_data.py.txt](https://github.com/user-attachments/files/17866747/download_data.py.txt)
[download_data.yml.txt](https://github.com/user-attachments/files/17866748/download_data.yml.txt)
[geoschem_config.txt](https://github.com/user-attachments/files/17866749/geoschem_config.txt)
[HEMCO_Config.rc.txt](https://github.com/user-attachments/files/17866750/HEMCO_Config.rc.txt)

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Personal computer

### What compiler and version were you using?

Python 2.7.18

### Will you be addressing this bug yourself?

Yes, but I will need some help

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Carbon

### As what resolution were you running GEOS-Chem?

0.5*0.625

### What meterology fields did you use?

GEOS-FP
