### ISSUE TITLE
Deposition for new species (wet and dry)

### ISSUE THREAD

**Issue by IshirDutta** [geoschem/geos-chem#2706]
### Your name

Ishir Dutta

### Your affiliation

MIT

### What happened? What did you expect to happen?

I added a couple of new species to the model in order to better account for reactive nitrogen mass conservation. However, when I run the model, they display a banded WetLossConv output, and are not included in the dry deposition diagnostic.

I would expect the dry deposition to looks something like this (but there is no output for my added species)
![Image](https://github.com/user-attachments/assets/53e0826b-549e-406a-b0c6-aa392908383f)

And I would expect the wet deposition to look something like this (IONITA wet loss at 810 hPa in Apr 2016):
![Image](https://github.com/user-attachments/assets/789cef05-31bc-4e3a-aa41-f0c19aabdb1e)

But the output looks like this!
![Image](https://github.com/user-attachments/assets/63b7a321-bc44-472e-9de4-bcaee6cde9d7)

### What are the steps to reproduce the bug?

Here's one example of what I did for ALKONITA:

1. Added ALKONITA to custom.eqn in KPP (modeled after IONITA formation and hydrolysis):
`ALKONITA   = IGNORE; {Aerosol-phase organic nitrate from R4N2 uptake; >=C4 alkylnitrates}`

`R4N2 = ALKONITA :                VOCuptk1stOrd( SR_MW(ind_R4N2), 5.0E-3_dp, State_Het ); `
`ALKONITA = INDIOL + HNO3 :       2.78d-04; `
 
2. Add ALKONITA to species_database (given the same properties as IONITA):
```
ALKONITA:
  DD_DvzAerSnow: 0.03
  DD_F0: 0.0
  DD_Hstar: 0.0
  FullName: Aer-phase ALK4 organic nitrate from R4N2 uptake
  Is_Advected: true
  Is_Aerosol: true
  Is_DryDep: true
  Is_WetDep: true
  MW_g: 119.10
  WD_AerScavEff: 0.8
  WD_KcScaleFac: [1.0, 0.5, 1.0]
  WD_RainoutEff: [0.8, 0.0, 0.8]
  WD_RainoutEff_Luo: [0.4, 0.0, 0.8]
```

I also had to increase a the default KPP EQN_LENGTH to 350 to accommodate all the (mostly non-advected) tracers I've added to my simulation, but I doubt that this is the source of the issue.

### Please attach any relevant configuration and log files.

I'm attaching what I think are the most relevant files, but let me know if I'm missing anything. Thanks!

[custom_eqn.txt](https://github.com/user-attachments/files/18630648/custom_eqn.txt)
[geoschem_config_yml.txt](https://github.com/user-attachments/files/18630647/geoschem_config_yml.txt)
[HISTORY_rc.txt](https://github.com/user-attachments/files/18630649/HISTORY_rc.txt)
[species_database_yml.txt](https://github.com/user-attachments/files/18630650/species_database_yml.txt)

### What GEOS-Chem version were you using?

14.3.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 6.3.1

### Will you be addressing this bug yourself?

Yes, but I will need some help

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

2x2.5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment]
Thanks for writing @IshirDutta.  I noticed you are using a GNU compiler that is pretty old.  We would recommend using version 10 or later if possible as we have sometimes seen some weird behavior with the older compilers.

Have you looked at the ALKONITA concentration field (in SpeciesConc)?  I wonder if the convective loss plot is a side-effect of weird concentration values.

It could also be possible that you have an out-of-bounds or other error happening.  I would recommend trying a short simulation (1 hour) with `-DCMAKE_RELEASE_TYPE=Debug` just to rule out this possibility.

**Comment by IshirDutta** [comment]
Both great questions! I figured you'd note that the compiler was ancient as I was typing out the issue, so I'm already working on upgrading it! I'll run a short simulation too and report back.

I did look at the SpeciesConc fields and they appear to be pretty normal (ALKONITA and IONITA for reference attached below):

![Image](https://github.com/user-attachments/assets/6de03d91-1276-42de-9ed7-8f22655945bb)

![Image](https://github.com/user-attachments/assets/e2f44d56-0324-4b34-9ac3-677b713c5a8c)

**Comment by IshirDutta** [comment]
Here's the output of the 1-hour simulation. I scanned through the log file but didn't see anything particularly out of the ordinary. I did notice that the number of dry dep species cuts off at 160. Is this a hard coded limit somewhere? That would at least explain half the problem!

[log-336268-out.txt](https://github.com/user-attachments/files/18694568/log-336268-out.txt)

**Comment by yantosca** [comment]
@IshirDutta: I believe there shouldn't be a hard-coded limit on drydep species.  But I believe the model computes nDryDep by checking the defined species that have Is_DryDep = true in the species_database.yml file at the start of the run.

In the 1-hour log file I noticed this:
```console
ModelId         :      421
Name            : ALKONITA
FullName        : Aer-phase ALK4 organic nitrate from R4N2 uptake
Formula         : UNKNOWN
MW_g            :   119.10
Gas or aerosol  : AEROSOL
Is_Kpp          : T
KppSpcId        :      216
Is_ActiveChem   : T
KppVarId        :      216
Is_WetDep       : T
WetDepID        :      147
WD_AerScavEff   :  8.000000E-01
WD_KcScaleFac   :     1.00     0.50     1.00
WD_RainoutEff   :     0.80     0.00     0.80
BackgroundVV    :  1.000000E-20
```
It doesn't say that ALKONITA is a drydep species although it is listed in the species_database.yml:
```yaml
ALKONITA:
  DD_DvzAerSnow: 0.03
  DD_F0: 0.0
  DD_Hstar: 0.0
  FullName: Aer-phase ALK4 organic nitrate from R4N2 uptake
  Is_Advected: true
  Is_Aerosol: true
  Is_DryDep: true
  Is_WetDep: true
  MW_g: 119.10
  WD_AerScavEff: 0.8
  WD_KcScaleFac: [1.0, 0.5, 1.0]
  WD_RainoutEff: [0.8, 0.0, 0.8]
  WD_RainoutEff_Luo: [0.4, 0.0, 0.8]
```
but ALKONITA also doesn't seem to have a drydep index given to it:
```console
===============================================================================
SPECIES NAMES AND INDICES

Name               ModelId  DryDepId  WetDepId  PhotolId HygGrthId  KppSpcId
-------------------------------------------------------------------------------

ALKONITA               421         -       147         -         -       216
```
I think this is because ALKONITA hasn't been added to the list of advected species in `geoschem_config.yml`.  Only the advected species can be dry or wet deposited.
