### ISSUE TITLE
NOx ensemble member run with offline chemistry

### ISSUE THREAD

**Issue by cschooling** [geoschem/geos-chem#2804]
### Your name

Chloe Schooling

### Your affiliation

The University of Edinburgh 

### Please provide a clear and concise description of your question or discussion topic.

Hi, I have added some additions to the carbon run source code, in order to add the chemical species NOx. 

This has worked well and gets reasonable agreement in comparison to Full Chemistry model runs. 
The changes I have made to KPP include adding in the additional reactions in carbon.eqn:
```
NOx             = Dummy             : k_Trop(4);
DummytoNOx      = NOx               : k_Trop(5);
```
Then I determine the chemical rates within carbon_Funcs.F90: 
```
 loss = LNOx_chem*C(ind_NOx)/NOx_lev
 prod = PNOx_chem*C(ind_NOx)/NOx_lev
 k_Trop(4) = loss   /C(ind_NOx)
 k_Trop(5) = prod 
```
Where LNOx_chem, PNOx_chem, and NOx_lev are read in using HEMCO (they are rates, and concentrations from a full chemistry run). As I found that scaling the nox chemical rates by relative differences in the nox concentration compared to a baseline full chem run is a pretty good approximation.  I also integrated the nox species into the carbon_gases_mod.F90 script within GeosCore. 

All of this works to model and investigate transport/emissions of atmiospheric NOx more efficiently than turning on the full chemistry mechanism. 

The reason I have done this is in order to explore inversion work to improve NOx emissions estimates. I am hoping to run this using an ensemble kalman filter (ENKF) approach. This involves running the simulation with many different NOx ensemble members all with different emission scaling factors. I am trying to run with 100 ensemble members, which I label NOx_E1, .., NOx_E100. I add them into the species database like so: 
```
NOx_PROP: &NOxproperties
  Formula: NOx
  Is_Advected: true
  Is_DryDep: true
  Is_Gas: true
  Is_Photolysis: true
  MW_g: 30.01 
NOx:
  << : *NOxproperties
  Background_VV: 4.0e-13
  FullName: Nitrogen Oxides
NOx_E1:
  << : *NOxproperties
  Background_VV: 4.0e-13
  FullName: Nitrogen Oxides. 
```
And I introduce emissions as each ensemble member in HEMCO_Config.rc. What I have found is that, the species called NOx is decaying as expected, but the ensemble members do not decay (concentrations are very elevated in comparison). I wasn't sure if anyone would be able to advice me on the most efficient way to implement the analogous NOx decay for each of these members.  Would I need to set this up as: 
```
NOx_E1             = Dummy             : k_Trop(6);
DummytoNOx      = NOx_E1              : k_Trop(7);
```
with: 
```
 loss = LNOx_chem*C(ind_NOx_E1)/NOx_lev
 prod = PNOx_chem*C(ind_NOx_E1)/NOx_lev
 k_Trop(6) = loss   /C(ind_NOx)
 k_Trop(7) = prod 
```
And manually add all 100 ensemble members into the source code, or is there a more efficient way to do this?
Thanks a lot!
