### ISSUE TITLE
Matching the v.14.3.0 benchmark output (issue with Soil NOx and Biogenic VOC)

### ISSUE THREAD

**Issue by erinemme** [geoschem/geos-chem#2834]
### Your name

Erin Emme

### Your affiliation

University of Illinois at Urbana-Champaign

### Please provide a clear and concise description of your question or discussion topic.

Hello, 
I am trying to compare a simulation to the v.14.3.0 HEMCO diagnostics output and am having some difficulties with Soil NOx and Biogenic VOCs. I first had emissions offline, and had differences in everything (sea salt, dust, soil NOx, biogenics). Once I turned everything online, I was able to get sea salt and dust emissions to match the benchmark but am still seeing differences in Soil NOx and Biogenics. 

Here are the differences in Soil NOx with the emissions offline:

<img width="738" alt="Image" src="https://github.com/user-attachments/assets/a5e1e3e9-5b62-429a-9eea-7c66a434b4ed" />

And then turned online:

<img width="741" alt="Image" src="https://github.com/user-attachments/assets/89da5cb1-cc68-4f6d-b1a0-adca9ef2a616" />

And here is an example of biogenic VOC (Isoprene) with emissions offline:

<img width="740" alt="Image" src="https://github.com/user-attachments/assets/ac88b1bb-0365-41a2-94d4-e83d4de09f5a" />

and online:

<img width="738" alt="Image" src="https://github.com/user-attachments/assets/a34885d5-cc38-4c99-9743-47d1cf231588" />

Note that the difference in emissions is an order of magnitude larger with emissions online. Are there any suggestions as to how I can make sure I am able to match the emissions from the benchmark?

Thank you, 
Erin Emme

**Comment by erinemme** [comment]
Hello Bob, 
I'm unable to open the link you sent

<img width="701" alt="Image" src="https://github.com/user-attachments/assets/6ed8eab1-56c4-45a5-819b-88c91bd44d97" />

could you please send again?

**Comment by yantosca** [comment]
@erinemme: Sorry, the link above is broken.  Try this one from my dropbox: 

- https://www.dropbox.com/scl/fi/55g9t4nee7ozh99qpdzl0/RunGCC_OutputDir.tar?rlkey=t3x5anf5i7qiduxu2fkxxk7b9&st=r58iccne&dl=0

Also if you would like to run the emissions benchmark plots, you can see these instructions on GCPy:

- https://gcpy.readthedocs.io/en/stable/Benchmarking.html

You could use these settings in the 1mo_benchmark.yml file:
```yaml
#
# comparisons: Specifies the comparisons to perform.
#
comparisons:
  gcc_vs_gcc:
    run: True
    dir: GCC_version_comparison
    tables_subdir: Tables
  gchp_vs_gcc:
    run: False
    dir: GCHP_GCC_comparison
    tables_subdir: Tables
  gchp_vs_gchp:
    run: False
    dir: GCHP_version_comparison
    tables_subdir: Tables
  gchp_vs_gcc_diff_of_diffs:
    run: False
    dir: GCHP_GCC_diff_of_diffs
#
# outputs: Specifies the plots and tables to generate
#
outputs:
  plot_conc: False
  plot_emis: True
  emis_table: True
  plot_jvalues: False
  plot_aod: False
  plot_drydep: False  # Need to save out DryDep collection for 1-mo
  mass_table: False
  mass_accum_table: False
  ops_budget_table: False
  OH_metrics: False
  ste_table: True # GCC only
  timing_table: False
  summary_table: False
  plot_options:
    by_spc_cat: True
    by_hco_cat: True
```
