### ISSUE TITLE
AOD simulation

### ISSUE THREAD

**Issue by grandeamore333** [geoschem/geos-chem#2854]
### Your name

lin

### Your affiliation

lanzhou university

### Please provide a clear and concise description of your question or discussion topic.

Hello！I used geoschem to simulate a dust process and wanted to use the model to simulate AOD to verify the simulation results. However, I found that the AODDust part I simulated had no numerical values. How do I need to modify it to obtain the simulation of AOD? The following is my file configuration.Thank you!!!!
```yaml
---
### geoschem_config.yml: GEOS-Chem Runtime configuration options.
### Customized for simulations using the aerosols-only mechanism.
###
### NOTE: Add quotes around nitrogen oxide ('NO'), because YAML
### parsers will confuse this with a negative "no" value.

#============================================================================
# Simulation settings
#============================================================================
simulation:
  name: aerosol
  start_date: [20210301, 000000]
  end_date: [20210331, 000000]
  root_data_dir: /public/home/lzu_chsy/linshy/geos/ExtData
  met_field: MERRA2
  species_database_file: ./species_database.yml
  species_metadata_output_file: OutputDir/geoschem_species_metadata.yml
  verbose:
    activate: false
    on_cores: root       # Allowed values: root all
  use_gcclassic_timers: false

#============================================================================
# Grid settings
#============================================================================
grid:
  resolution: 2.0x2.5
  number_of_levels: 72
  longitude:
    range: [-180.0, 180.0]
    center_at_180: true 
  latitude:
    range: [-90.0, 90.0]
    half_size_polar_boxes: true 
  nested_grid_simulation:
    activate: false
    buffer_zone_NSEW: [0, 0, 0, 0]

#============================================================================
# Timesteps settings
#============================================================================
timesteps:
  transport_timestep_in_s: 600
  chemistry_timestep_in_s: 1200

#============================================================================
# Settings for GEOS-Chem operations
#============================================================================
operations:

  chemistry:
    activate: false

  convection:
    activate: true

  dry_deposition:
    activate: true
    CO2_effect:
      activate: false
      CO2_level: 600.0
      reference_CO2_level: 380.0
    diag_alt_above_sfc_in_m: 10

  pbl_mixing:
     activate: true
     use_non_local_pbl: true 

  photolysis:
    activate: true
    cloud-j:
      cloudj_input_dir: /public/home/lzu_chsy/linshy/geos/ExtData/CHEM_INPUTS/CLOUD_J/v2025-01/
      num_levs_with_cloud: 34
      cloud_scheme_flag: 3
      opt_depth_increase_factor: 1.050
      min_top_inserted_cloud_OD: 0.005
      cloud_overlap_correlation: 0.33
      num_cloud_overlap_blocks: 6
      sphere_correction: 1
      num_wavelength_bins: 18
      use_H2O_UV_absorption: true
    input_directories:
      fastjx_input_dir: /public/home/lzu_chsy/linshy/geos/ExtData/CHEM_INPUTS/FAST_JX/v2024-05/
      cloudj_input_dir: /public/home/lzu_chsy/linshy/geos/ExtData/CHEM_INPUTS/CLOUD_J/v2024-09/
    overhead_O3:
      use_online_O3_from_model: false
      use_column_O3_from_met: true
      use_TOMS_SBUV_O3: false
    photolyze_nitrate_aerosol:
      activate: true
      NITs_Jscale: 100.0
      NIT_Jscale: 100.0
      percent_channel_A_HONO: 66.667
      percent_channel_B_NO2: 33.333

  rrtmg_rad_transfer_model:
    activate: false

  transport:
    gcclassic_tpcore:                 # GEOS-Chem Classic only
      activate: true                  # GEOS-Chem Classic only
      fill_negative_values: true      # GEOS-Chem Classic only
      iord_jord_kord: [3, 3, 7]       # GEOS-Chem Classic only
    transported_species:
      - BCPI
      - BCPO
      - DMS
      - DST1
      - DST2
      - DST3
      - DST4
      - H2O2
      - MSA
      - NH3
      - NH4
      - NIT
      - NITs
      - OCPI
      - OCPO
      - pFe
      - SALA
      - SALAAL
      - SALACL
      - SALC
      - SALCAL
      - SALCCL
      - SO2
      - SO4
      - SO4s
      - SOAP
      - SOAS

  wet_deposition:
    activate: true

#============================================================================
# Settings for GEOS-Chem aerosols
#============================================================================
aerosols:

  optics:
    input_dir: /public/home/lzu_chsy/linshy/geos/ExtData/CHEM_INPUTS/Aerosol_Optics/v2025-03/

  carbon:
    activate: true
    brown_carbon: true
    enhance_black_carbon_absorption:
      activate: true
      hydrophilic: 1.5
      hydrophobic: 1.0

  dust:
    activate: true
    acid_uptake_on_dust: false

  sea_salt:
    activate: true
    SALA_radius_bin_in_um: [0.01, 0.5]
    SALC_radius_bin_in_um: [0.5,  8.0]
    marine_organic_aerosols: false

  stratosphere:
    settle_strat_aerosol: false

  sulfate:
    activate: true
    metal_cat_SO2_oxidation: true

#============================================================================
# Settings for diagnostics (other than HISTORY and HEMCO)
#============================================================================
extra_diagnostics:

  obspack:
    activate: false
    quiet_logfile_output: false
    input_file: ./obspack_input_for_testing.20190701.nc
    output_file: ./OutputDir/GEOSChem.ObsPack.YYYYMMDD_hhmmz.nc4
    output_species:
      - BCPI
      
  planeflight:
    activate: false
    flight_track_file: Planeflight.dat.YYYYMMDD
    output_file: ./OutputDir/plane.log.YYYYMMDD
```
