### ISSUE TITLE
dust simulation

### ISSUE THREAD

**Issue by grandeamore333** [geoschem/geos-chem#2857]
### Your name

lin

### Your affiliation

lanzhou university

### Please provide a clear and concise description of your question or discussion topic.

Hello, dear GC team. My version of geoschem is 14.6.0. When I was using geoschem to simulate the dust process, I encountered a problem. I opened the offline dust module, but the value of AODDust in the output result was 0. I had to use AOD to verify the simulation result. Up to now, I still haven't found a solution. I hope you can give me some suggestions. The following is my configuration file. Thank you very much!!
[HISTORY.rc.txt](https://github.com/user-attachments/files/20299685/HISTORY.rc.txt)

[HEMCO_Config.rc.txt](https://github.com/user-attachments/files/20299713/HEMCO_Config.rc.txt)

[geoschem_config.yml.txt](https://github.com/user-attachments/files/20299756/geoschem_config.yml.txt)

[HEMCO_Diagn.rc.txt](https://github.com/user-attachments/files/20299747/HEMCO_Diagn.rc.txt)

**Comment by yantosca** [comment]
Thanks @grandeamore333 for writing.  I think the issue is that RDUST_Online is being called with WAVELENGTH=0 (use 1000nm, I think?) instead of WAVELENGTH=1.  Using WAVELENGTH=1 will toggle the code that archives the AODdust diagnostic.

Untangling this may be a little more involved than I thought at first, so there may not be a fast solution here.

**Comment by grandeamore333** [comment]
> Thanks [@grandeamore333](https://github.com/grandeamore333) for writing. I think the issue is that RDUST_Online is being called with WAVELENGTH=0 (use 1000nm, I think?) instead of WAVELENGTH=1. Using WAVELENGTH=1 will toggle the code that archives the AODdust diagnostic.
> 
> Untangling this may be a little more involved than I thought at first, so there may not be a fast solution here.

Thank you very much for your suggestion. However, I haven't found in which file to modify the WAVELENGTH variable you mentioned. Could you please tell me again? Thank you very much!

**Comment by yantosca** [comment]
Oops my bad.  It's in `GeosCore/dust_mod.F90`.  The variable `WAVELENGTH` is passed into the `ODSWITCH` dummy argument in `RDUST_ONLINE`.  The code that currently updates the `AODDust*` diagnostics only executes when `ODSWITCH` is 1.

That code could stand a good cleaning up, as it was written a while ago.

**Comment by yantosca** [comment]
@grandeamore333 @lizziel: I figured out why the `AODDust` diagnostic was coming up all zeros for the aerosol-only simulation.  The `GEOS-Chem/run/geoschem_config.yml.templates/geoschem_config.yml.aerosol` template file does not have the `aod_wavelengths_in_nm` field specified.  

To fix this, add the following lines to your `geoschem_config.yml` file under the `operations` section:

```yaml
operations:
  chemistry:
    ... etc not shown ...

  convection:
    ... etc not shown ...


  dry_deposition:
    ... etc not shown ...

  pbl_mixing:
    ... etc not shown ...

  photolysis:
    ... etc not shown ...
     
  # Add these lines here!!!!
  rrtmg_rad_transfer_model:           # NOTE: This menu is only used
    aod_wavelengths_in_nm:            # to specify the AOD wavelength.
      - 550                           # the fullchem simulations.

  transport:
   ... etc not shown ...
```

I ran an 1-hr simulation just as a sanity check and the `AODDust` output did have nonzero values:

![Image](https://github.com/user-attachments/assets/5a3b9ad7-d089-4087-ae2f-d6b1fe557e46)

The reason being is that the AOD code in `GeosCore/aerosol_mod.F90` needs to read the wavelength as input.  However there was a silent bug that if the wavelength was not specified, the run would continue but the `AODDust` diagnostic would be all zeroes.  I will push a fix for the `geoschem_config.yml.aerosol` template file and also introduce an error message if an AOD wavelength is not specified.
