### ISSUE TITLE
READ_DRYDEP_INPUTS: Opening /root/ExtData/CHEM_INPUTS/Olson_Land_Map_201203/Olson_2001_Drydep_Inputs.nc

### ISSUE THREAD

**Issue by lizhenhua20160506** [geoschem/geos-chem#2898]
### Your name

lizhenhua

### Your affiliation

self

### Please provide a clear and concise description of your question or discussion topic.

yes, i installed geos-chem and change date to 20210701-20210801 then dryrun and download data by download.py,
then run ./gcclassic  ,
'READ_DRYDEP_INPUTS: Opening /root/ExtData/CHEM_INPUTS/Olson_Land_Map_201203/Olson_2001_Drydep_Inputs.nc' , 
Where can I download this file? Can I download it through download.py?
I didn't change any files, just changed the time. I used version 14.6.

**Comment by yantosca** [comment]
Thanks @lizhenhua20160506.  You can get this file from one of the links below:

- https://geos-chem.s3-us-west-2.amazonaws.com/CHEM_INPUTS/Olson_Land_Map_201203/Olson_2001_Drydep_Inputs.nc

- http://geoschemdata.wustl.edu/ExtData/CHEM_INPUTS/Olson_Land_Map_201203/Olson_2001_Drydep_Inputs.nc

**Comment by yantosca** [comment]
@lizhenhua20160506 if the s3://geos-chem bucket is not reachable from your location, you can edit the download_data.yml file accordingly:
```yaml
  # GEOS-Chem Input Data portal, download via HTTP/wget
  # NOTE: Use geoschemdata.wustl.edu as a backup
  geoschem+http:
    short_name: gh
    s3_bucket: False
    #remote: https://geos-chem.s3-us-west-2.amazonaws.com    # <== make sure this line starts with a "#"
    remote: http://geoschemdata.wustl.edu/ExtData            # <== make sure this line does not start with a "#"
    command: 'wget -r -np -nH -R "*.html" -N -P @PATH@ '
    quote: '"'
```
