### ISSUE TITLE
[QUESTION] AOD diagnostics in v13.0.0

### ISSUE THREAD

**Issue by kbilsback** [geoschem/geos-chem#603]
Dear GC Team,
I am using v13.0.0 and would like to output AOD tracers to compare to AERONET. I tried using the "AODHygWL1_<spcname>" diagnostic in the AEROSOLS menu of HISTORY.rc; however, it appears that this is only the hygroscopic component of AOD. Is there a way for me to output the full AOD, not just the hygroscopic component? In the past, I had used the tracers 517-522 in the ND49 menu, but I haven't been able to find where these tracers ended up in the HISTORY.rc diagnostics and I don't see an option for using ND49 in v13.0.0. Thanks!

**Comment by yantosca** [comment]
Hi @kbilsback, thanks for writing.  For the GEOS-Chem benchmarks, we use these diagnostics to create the total AOD in the benchmarks:
```yaml
diag name,  plot name in PDF
AODDust: Column_AOD_Dust
AODHyg550nm_BCPI: Column_AOD_BCPI
AODHyg550nm_OCPI: Column_AOD_OCPI
AODHyg550nm_SALA: Column_AOD_SALA
AODHyg550nm_SALC: Column_AOD_SALC
AODHyg550nm_SO4: Column_AOD_SO4
AODPolarStratCloud550nm: Column_AOD_Polar_Strat_Cloud
AODSOAfromAqIsoprene550nm: Column_AOD_SOA_from_Aqueous_ISOP
AODStratLiquidAer550nm: Column_AOD_Strat_Liquid_Aerosol
AODTotal: Column_AOD_Total
```
And here is a [sample AOD plot](http://ftp.as.harvard.edu/gcgrid/geos-chem/1mo_benchmarks/GC_13/13.0.0-beta.0/GCHP/BenchmarkResults/GCHP_version_comparison/Aerosols/Aerosols_ColumnOptDepth.pdf) from the benchmarks.
