### ISSUE TITLE
[FEATURE REQUEST] Specifying species other than HNO3 and O3 with ConcAboveSfc Collection

### ISSUE THREAD

**Issue by wswanson3** [geoschem/geos-chem#611]
# Request a new GEOS-Chem feature

The ConcAboveSfc collection is quite useful for looking at surface ozone mixing ratios. Where could I modify the code to retrieve surface BrO mixing ratios? Would it be possible to add a feature to specify ConcAboveSfc species of interest (O3, HNO3, BrO or other) in input.geos in the same place that the height above surface is defined?

**Comment by yantosca** [comment]
Thanks for writing @wswanson3.  I think you should just be able to add other species to the ConcAboveSfc collection by adding the `Is_DryAlt : true` to the `species_database.yml` file in your run directory:

For example, to add BrO to the ConcAfterSfc collection, make sure you have this:
```yaml
BrO:
  Formula: BrO
  FullName: Bromine monoxide
  Is_Advected: true
  Is_Gas: true
  Is_Photolysis: true
  MW_g: 95.90
  Is_DryAlt: true
```

Then as long as you have `SpeciesConc_?DRYALT?` requested in the `HISTORY.rc` file, you should get BrO output as well.

I believe that the reason we only have O3 and HNO3 is because most other species do not have as much of a vertical gradient between the midpoint of the first layer (~60 m) and the surface.  So we never bothered making it more general.
