### ISSUE TITLE
[DISCUSSION] Installing a Spack software stack for GEOS-Chem Classic

### ISSUE THREAD

**Issue by yantosca** [geoschem/geos-chem#637]
## Building software libraries with Spack for GEOS-Chem Classic

Here are some up-to-date instructions on installing a software stack for GEOS-Chem Classic with Spack.  I used gcc/gfortran 10.2.0 on the AWS Cloud (Ubuntu 18.04 Bionic Beaver) but these instructions should work for any cluster.

### Installing spack to your home directory
```
cd ~
$ git clone git@github.com:spack/spack.git
```

### Initialize Spack
Initialize spack (also add these commands to your ~/.bashrc or ~/.bash_aliases)
```
$ export SPACK_ROOT=${HOME}/spack
$ source ${SPACK_ROOT}/spack/share/spack/setup-env.sh
``` 
### Make sure the default compiler is in compilers.yaml
Open the compilers.yaml file with your favorite editor, e.g.:
```
$ emacs ~/.spack/linux/compilers.yaml
```
For example, the default compiler that was on my cloud instance was listed as:
```
compilers:
- compiler:
    spec: gcc@7.4.0
    paths:
      cc: /usr/bin/gcc-7
      cxx: /usr/bin/g++-7
      f77: /usr/bin/gfortran-7
      fc: /usr/bin/gfortran-7
    flags: {}
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

### Build GNU Compiler Collection 10.2.0 and load it
Let's build a newer compiler with Spack.  In this case we'll build gcc/gfortran 10.2.0 using the default compilers (gcc/gfortran 7.4.0).
```
$ spack install gcc@10.2.0 target=x86_64 %gcc@7.4.0
$ spack load gcc%10.2.0
```

### Update compilers.yaml with the compiler you just built
First, find the path to the compiler with the spack location command.  This will generate a very long path name such as this (yours will be different):
```
$ spack location -i gcc@10.2.0
/home/ubuntu/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/gcc-10.2.0-55gqd2sskfouetylmy7iozwreoie6rb4
```
Then open the compilers.yaml file with your favorite editor (mine is Emacs):
```
$ emacs ~/.spack/linux/compilers.yaml
```
And then add the long path name + `/bin` to the `cc`, `cxx`, `f77`, and `fc` entries in `compilers.yaml`.  For example, my new entry for gcc/gfortran 10.2.0 looked like this:
```
- compiler:
    spec: gcc@10.2.0
    paths:
      cc: /home/ubuntu/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/gcc-10.2.0-55gqd2sskfouetylmy7iozwreoie6rb4/bin/gcc
      cxx: /home/ubuntu/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/gcc-10.2.0-55gqd2sskfouetylmy7iozwreoie6rb4/bin/g++
      f77: /home/ubuntu/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/gcc-10.2.0-55gqd2sskfouetylmy7iozwreoie6rb4/bin/gfortran
      fc: /home/ubuntu/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/gcc-10.2.0-55gqd2sskfouetylmy7iozwreoie6rb4/bin/gfortran
    flags: {}
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

### Install HDF5
Now we can start installing libraries.  First, let's install HDF5:
```
$ spack install hdf5%gcc@10.2.0 target=x86_64 +cxx+fortran+hl+pic+shared+threadsafe
$ spack load hdf5%gcc@10.2.0
```
### Install netCDF-Fortran and netCDF-C
Here we are going to tell Spack to install netCDF-Fortran (which installs netCDF-C), using the HDF5 library (with all of the relevant options) that we just built:
```
$ spack install netcdf-fortran%gcc@10.2.0 target=x86_64 ^hdf5+cxx+fortran+hl+pic+shared+threadsafe
$ spack load netcdf-fortran
$ spack load netcdf-c 
```

### Install ncview 
Ncview is a convenient viewer for browsing netCDF files.  Install it with:
```
$ spack install ncview%gcc@10.2.0  target=x86_64 ^hdf5+cxx+fortran+hl+pic+shared+threadsafe
$ spack load ncview%gcc@10.2.0
```
### Install the NetCDF Operators (NCO)
The netCDF operators are useful programs for manipulating netCDF files and attributes:
```
$ spack install nco%gcc@10.2.0 target=x86_64 ^hdf5+cxx+fortran+hl+pic+shared+threadsafe
$ spack load nco%gcc@10.2.0
```

### Install Climate Data Operators (CDO)
The Climate Data Operators (CDO) are utilities for processing data in netCDF files.
```
$ spack install cdo%gcc@10.2.0 target=x86_64 ^hdf5+cxx+fortran+hl+pic+shared+threadsafe
$ spack load cdo%gcc@10.2.0
```

### Install flex
The flex library is a lexical parser.  It is a dependency for [KPP-for-GEOS-Chem](https://kpp.readthedocs.io).
```
$ spack install flex%gcc@10.2.0 target=x86_64
$ spack load flex%gcc10.2.0
```

### Install GDB and CGDB
GDB is the GNU Debugger.  CGDB is a more user-friendly interface for GDB.

NOTE: You may find that the Spack installation of GDB won't build.  If that is the case, go ahead and build CGDB, and you can use the version of GDB that is already installed on your system.
```
$ spack install gdb@9.1%gcc@10.2.0 target=x86_64
$ spack load gdb%10.2.0

$ spack install cgdb%gcc@10.2.0 target=x86_64
$ spack load cgdb%gcc@10.2.0
```
### Install CMake and GMake
CMake and GMake are used to build source code into executables.  GEOS-Chem 13.0.0 and later uses CMake by default, but you may need GMake to build other software packages, so it's good to have both installed.
```
$ spack install cmake%gcc@10.2.0 target=x86_64
$ spack load cmake%gcc@10.2.0

$ spack install gmake%gcc@10.2.0 target=x86_64
$ spack load gmake%gcc@10.2.0
```
