### ISSUE TITLE
[BUG/ISSUE] molecular weight for OH and other non-advected species

### ISSUE THREAD

**Issue by jingqiumao** [geoschem/geos-chem#697]
### Description of the problem
It seems that the molecular weights for OH and HO2 (and probably many others) are 1 g/mol, instead of 17g/mol and 33 g/mol. And this has been used in flexchem_mod.F90 to change these species from kg to moleculec/cm3 and back. Should we use the correct molecular weights for these non-advected species?

I am trying to play with OH in flexchem_mod.F90, but the wrong molecular weight has caused issues.

### GEOS-Chem version
12.5.0

### Description of modifications
Describe your modifications here.

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:

**Comment by jingqiumao** [comment]
Just want to check if I change the molecular weight for OH and HO2 to 17 and 33 g/mol in species_database_mod.F90, it will be OK.

**Comment by msulprizio** [comment]
Thanks for writing. Traditionally in GEOS-Chem the non-advected species were not assigned properties, like molecular weight. In [GEOS-Chem 12.9.0](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_12#12.9.0) we converted the species database to a YAML file. Those updates also included:

- [Defining all species properties in the species database, not just advected species](https://github.com/geoschem/geos-chem/issues/110)
- [Initializing the species database with values read from the YAML file](https://github.com/geoschem/geos-chem/issues/216)

See the current [species_database.yml](https://github.com/geoschem/geos-chem/blob/main/run/shared/species_database.yml) file for the current defined properties for all species. For HO2 and OH, we use:

```
HO2:
  Background_VV: 4.0e-15
  Formula: HO2
  FullName: Hydroperoxyl radical
  Is_Gas: true
  MW_g: 33.01
OH:
  Background_VV: 4.0e-15
  Formula: OH
  FullName: Hydroxyl radical
  Is_Gas: true
  MW_g: 17.01
```
